#!/bin/sh
set -e

cd ~

# Only mac book (OSX)
# Install Homebrew
if [ ! -f /usr/local/bin/brew ]
	then
		echo "Installing Homebrew..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
	else
		echo "Homebrew already installed."
fi

# Clone my dotfiles
if [ ! -d ~/dotfiles ]
	then
		cd ~/.ssh
		ssh-keygen
		pbcopy < ~/.ssh/id_rsa.pub
		echo "公開鍵をGitHubに登録しましたか？"
		select yn in "Yes"; do
			case $yn in
				Yes ) break;;
			esac
		done

		echo "Cloning dotfiles..."
		git clone git@github.com:watsuyo/dotfiles.git
	else
		echo "dotfiles already cloned."
fi

echo "シンボリックリンクを貼る"
echo "Symlinking dotfiles..."
cd dotfiles
IGNORE_PATTERN="^\.(git|gitignore|config)"
for dotfile in .??*; do
    [[ $dotfile =~ $IGNORE_PATTERN ]] && continue
    ln -snfv "$(pwd)/$dotfile" "$HOME/$dotfile"
done