# 全部入り
[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
merged = '0'
build = 'coc#util#install()'
hook_source = '''
" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice.
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
      \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
" 目印とかがなくても余白を開ける
set signcolumn=yes
'''

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
" 0: never 1: only split 2: always
set laststatus=2
let g:lightline = {
\	'active': {
\		'left': [ ['mode', 'paste'], ['readonly', 'filename', 'modified'] ]
\	},
\}
'''
