## lsp
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

# 補完plugin
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'

# 補完source
[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

# 補完filter
[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

# help日本語
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_source = 'set helplang=ja,en'

# SKK
[[plugins]]
repo = 'vim-skk/eskk.vim'
hook_add = '''
let g:eskk#large_dictionary = {
\ 'path': "~/dotfiles/SKK-JISYO.ML",
\ 'sorted': 1,
\ 'encoding': 'euc-jp',
\ }
'''

# 翻訳
[[plugins]]
repo = 'skanehira/translate.vim'

# gccでコメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
" 0: never 1: only split 2: always
set laststatus=2
'''

# カッコ補完
[[plugins]]
repo = 'cohama/lexima.vim'

# surround
[[plugins]]
repo = 'tpope/vim-surround'

# BadApple
[[plugins]]
repo = 'skanehira/badapple.vim'
