## lsp
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
let g:lsp_diagnostics_enabled = 0
let g:lsp_document_code_action_signs_enabled = 0
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

# 補完plugin
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']

# 補完source
[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

# 補完filter
[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

# あいまい検索
[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

# help日本語
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_source = 'set helplang=ja,en'

# SKK
[[plugins]]
repo = 'vim-skk/eskk.vim'
hook_add = '''
let g:eskk#large_dictionary = {
\ 'path': "~/dotfiles/SKK-JISYO.ML",
\ 'sorted': 1,
\ 'encoding': 'euc-jp',
\ }
function L_eskk_get_mode()
	if (mode() == 'i') && eskk#is_enabled()
		return g:eskk#statusline_mode_strings[eskk#get_mode()]
	else
		return ''
	endif
endfunction
'''

# 翻訳
[[plugins]]
repo = 'skanehira/translate.vim'

# gccでコメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
" 0: never 1: only split 2: always
set laststatus=2
let g:lightline = {
\	'active': {
\		'left': [ ['mode', 'paste'], ['readonly', 'filename', 'eskk', 'modified'] ]
\	},
\	'component_function': {
\		'eskk': 'L_eskk_get_mode'
\	},
\}
'''

# カッコ補完
[[plugins]]
repo = 'cohama/lexima.vim'

# surround
[[plugins]]
repo = 'tpope/vim-surround'

# BadApple
[[plugins]]
repo = 'skanehira/badapple.vim'
