[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_source = 'denops.vim'
hook_source = '''
let s:ddu_config_json =<< trim MARK
	{
		"ui": "ff",
		"uiOptions": {
			"filer": {
				"toggle": true
			}
		},
		"uiParams": {
			"ff": {
				"startFilter": true,
				"prompt": "> ",
				"autoAction" : { "name": "preview" },
				"filterSplitDirection": "floating",
				"split": "floating",
				"floatingBorder": "rounded",
				"floatingTitlePos": "center",
				"previewFloating":true,
				"previewFloatingBorder": "rounded",
				"previewFloatingTitle": [ ["Preview", "String"] ],
				"previewFloatingTitlePos": "center",
				"previewWindowOptions": [ ["&signcolumn", "no"], ["&wrap", 0], ["&number", 0] ]
			},
			"filer": {
				"split": "vertical",
				"splitDirection": "topleft",
				"sortTreesFirst": true
			}
		},
		"filterParams": {
			"matcher_fzf": {
				"highlightMatched": "String"
			},
			"matcher_substring": {
				"highlightMatched": "String"
			}
		},
		"kindOptions": {
			"file": {
				"defaultAction": "open"
			},
			"floaterm": {
				"defaultAction": "open"
			},
			"nvim_lsp": {
				"defaultAction": "open"
			},
			"command_history": {
				"defaultAction": "execute"
			},
			"help": {
				"defaultAction": "open"
			},
			"window": {
				"defaultAction": "open"
			},
			"tab": {
				"defaultAction": "open"
			}
		},
		"sourceOptions": {
			"rg": {
				"matchers": ["converter_display_word", "matcher_fzf"]
			},
			"file_rec": {
				"matchers": ["matcher_fzf"],
				"converters": ["converter_file_icon"]
			},
			"file_external": {
				"matchers": ["matcher_fzf"],
				"converters": ["converter_file_icon"]
			},
			"_": {
				"matchers": ["matcher_fzf"]
			}
		}
	}
MARK

let s:ddu_config_json = s:ddu_config_json->join('')->json_decode()

call ddu#custom#patch_global(s:ddu_config_json)

function! s:set_size() abort
	let winCol = &columns / 8
	let winWidth = &columns - (&columns / 4)
	let winRow = &lines / 8
	let winHeight = &lines - (&lines / 4)
	" window自体は左上が始点となる
	let s:ddu_config_json['uiParams']['ff']['winCol'] = winCol
	let s:ddu_config_json['uiParams']['ff']['winRow'] = winRow
	let s:ddu_config_json['uiParams']['ff']['winWidth'] = winWidth / 2
	let s:ddu_config_json['uiParams']['ff']['winHeight'] = winHeight
	" verticalオプションを使わないのもあって、previewの始点は左下になってる
	" あまりキレイじゃないのだ...
	let s:ddu_config_json['uiParams']['ff']['previewCol'] = winCol + winWidth / 2 + 2
	let s:ddu_config_json['uiParams']['ff']['previewRow'] = winRow + winHeight + 5
	let s:ddu_config_json['uiParams']['ff']['previewWidth'] = winWidth / 2
	let s:ddu_config_json['uiParams']['ff']['previewHeight'] = winHeight + 3
	call ddu#custom#patch_global(s:ddu_config_json)
endfunction

call s:set_size()

autocmd VimResized * call s:set_size()

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Files', 'FloatBorder']],
			\		}
			\ },
			\ 'sources': [{'name': 'file_rec', 'params': {}}]
			\ })<CR>
nmap <silent> [ddu]g <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Files', 'FloatBorder'], ['Git', 'FloatBorder']],
			\		}
			\ },
			\ 'sources': [{
			\	'name': 'file_external',
			\	'params': { 'cmd': ['git', 'ls-files'] }
			\ }]
			\ })<CR>
nmap <silent> [ddu]t <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Tab', 'FloatBorder']],
			\			'autoAction': { 
			\				'name': 'preview',
			\				'params': { 'border': ['+', '-', '+', '\|'] }
			\			},
			\		}
			\ },
			\ 'sources': [{'name': 'tab', 'params': { 'format': 'tab\|%n:%T:%w' }}]
			\ })<CR>
nmap <silent> [ddu]T <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Floaterm', 'FloatBorder']],
			\			'previewSplit': 'horizontal',
			\			'winCol': &columns / 8,
			\			'winRow': &lines / 2,
			\			'winWidth': &columns - (&columns / 4),
			\			'winHeight': &lines / 2 - 8,
			\			'previewCol': &columns / 8,
			\			'previewRow': 0,
			\			'previewWidth': &columns - (&columns / 4),
			\			'previewHeight': &lines / 2 - 8,
			\		}
			\ },
			\ 'sources': [{'name': 'floaterm'}]
			\ })<CR>
nmap <silent> [ddu]w <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Window', 'FloatBorder']],
			\			'autoAction': { 
			\				'name': 'preview',
			\			},
			\		}
			\ },
			\ 'sources': [{'name': 'window'}]
			\ })<CR>
nmap <silent> [ddu]l <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Line', 'String']],
			\		}
			\ },
			\ 'sources': [{'name': 'line', 'params': {}}],
			\ })<CR>
nmap <silent> [ddu]d <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Dein', 'Black']],
			\			'autoAction': {},
			\			'winCol' : &columns / 8,
			\			'winWidth' : &columns - (&columns / 4),
			\			'winRow' : &lines / 8,
			\			'winHeight' : &lines - (&lines / 4),
			\		}
			\ },
			\ 'sources': [{'name': 'dein'}],
			\ })<CR>
nmap <silent> [ddu]j <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['JumpList', 'String']],
			\		}
			\ },
			\ 'sources': [{'name': 'jumplist', 'params': {}}],
			\ })<CR>
nmap <silent> [ddu]h <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Help', 'FloatBorder']],
			\		}
			\ },
			\ 'sources': [{'name': 'help', 'params': {}}],
			\ })<CR>
nmap <silent> [ddu]q <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'prompt': 'qf',
			\			'floatingTitle': [['QuickFix', 'String']],
			\		}
			\ },
			\ 'sources': [
			\	{
			\		'name': 'qf',
			\		'params': {
			\			'isSubset': v:true,
			\			'format': '%p\|%t',
			\ 		}
			\	},
			\ ],
			\})<CR>
" live grep
nmap <silent> [ddu]r <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'ignoreEmpty': v:false,
			\			'autoResize': v:false,
			\			'floatingTitle': [['Live Grep', 'String']],
			\		}
			\ },
			\ 'sources': [
			\	{
			\		'name': 'rg',
			\ 		'options': {'matchers': [], 'volatile': v:true},
			\	},
			\ ],
			\})<CR>
nmap <silent> [ddu]b <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Buffer', 'Blue']],
			\		}
			\ },
			\ 'sources': [{'name': 'buffer'}],
			\ })<CR>
nmap <silent> [ddu]c <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'sources': [{'name': 'command_history'}],
			\ })<CR>
nmap <silent> [ddu]lr <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'sources': [
			\	{'name': 'nvim_lsp', 'params': { 'method': 'textDocument/references' }}
			\ ],
			\ })<CR>
nmap <silent> [ddu]ld <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'sources': [
			\	{'name': 'nvim_lsp', 'params': { 'method': 'textDocument/definition' }}
			\ ],
			\ })<CR>
nmap <silent> [ddu]ls <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'sources': [
			\	{'name': 'nvim_lsp', 'params': { 'method': 'workspace/symbol' }}
			\ ],
			\ })<CR>
nmap <silent> [ddu]lc <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'fuiParams': {
			\	'ff': {
			\		'displayTree': v:true,
			\		'startFilter': v:false,
			\	}
			\ },
			\ 'sources': [
			\	{'name': 'nvim_lsp', 'params': { 'method': 'callHierarchy/incomingCalls' }}
			\ ],
			\ })<CR>
nmap <silent> [ddu]e <Cmd>call ddu#start({
			\ 'ui': 'filer',
			\ 'sources': [{'name': 'file'}],
			\ 'sourceOptions': {'_': {'columns': ['icon_filename']}},
			\ 'uiParams': {
			\	'filer': {
			\		'split': 'vertical',
			\		'splitDirectoin': 'topleft',
			\		'winWidth': &columns / 6,
			\	}
			\ },
			\ })<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-ff = '''
setlocal cursorline
setlocal signcolumn=yes
nnoremap <buffer><silent> <CR>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> <Space>
			\ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> i
			\ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent> p
			\ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
nnoremap <buffer><silent> e
			\ <Cmd>call ddu#ui#ff#do_action('expandItem')<CR>
nnoremap <buffer><silent> q
			\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
autocmd CursorMoved <buffer> call s:update_cursor()
function! s:update_cursor()
	sign unplace 100
	sign define cursor text=>> texthl=Constant
	execute printf('sign place 100 line=%d name=cursor buffer=%s',
		\ '.'->line(), '%'->bufnr())
endfunction
'''
ddu-ff-filter = '''
nnoremap <buffer> <CR>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> q
			\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
inoremap <buffer> <CR>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
inoremap <buffer> <C-t>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'tabnew'}})<CR>
inoremap <buffer> <C-o>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'split'}})<CR>
inoremap <buffer> <C-v>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'vsplit'}})<CR>
inoremap <buffer> <C-n>
			\ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')+1,0)<Bar>redraw")<CR>
inoremap <buffer> <C-p>
			\ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')-1,0)<Bar>redraw")<CR>
inoremap <buffer> <C-s>
			\ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
inoremap <buffer> <C-a>
			\ <Cmd>call ddu#ui#ff#do_action('toggleAllItems')<CR>
inoremap <buffer> <C-l>
			\ <ESC><Cmd>call ddu#ui#ff#do_action('leaveFilterWindow')<CR>
inoremap <buffer> <C-q>
			\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-filer = '''
nnoremap <buffer><expr> <CR>
			\ ddu#ui#get_item()->get('isTree', v:false) ?
			\ "<Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>" :
			\ "<Cmd>call ddu#ui#do_action('itemAction', {'name': 'open'})<CR>"
nnoremap <buffer><silent> <Space>
			\ <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> o
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'split'}})<CR>
nnoremap <buffer><silent> v
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
nnoremap <buffer><silent> t
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'tabnew'}})<CR>
nnoremap <buffer><silent> %
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'newFile'})<CR>
nnoremap <buffer><silent> d
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'newDirectory'})<CR>
nnoremap <buffer><silent> R
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'rename'})<CR>
nnoremap <buffer><silent> q
			\ <Cmd>call ddu#ui#do_action('quit')<CR>
'''

# 補完Source

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'flow6852/ddu-source-qf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-command_history'
on_source = 'ddu.vim'

[[plugins]]
repo = 'uga-rosa/ddu-source-nvim_lsp'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-jumplist'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-tab'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-floaterm'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-window'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-treesitter'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-dummy'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

# 補完Filter
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-filter-converter_file_icon'
on_source = 'ddu.vim'

# 補完Kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

# icon
[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

# command
[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'ddu.vim'
