[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_source = 'denops.vim'
hooks_file = 'nvim/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-ff = '''
setlocal cursorline
setlocal signcolumn=yes
nnoremap <buffer><silent> <CR>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> t
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'tabnew'}})<CR>
nnoremap <buffer><silent> o
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'split'}})<CR>
nnoremap <buffer><silent> v
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'vsplit'}})<CR>
nnoremap <buffer><silent> <C-j>
			\ <Cmd>call ddu#ui#ff#do_action('kensaku')<CR>
nnoremap <buffer><silent> a
			\ <Cmd>call ddu#ui#ff#do_action('chooseAction')<CR>
nnoremap <buffer><silent> s
			\ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> i
			\ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent> c
			\ <Cmd>call ddu#ui#ff#do_action('closeFilterWindow')<CR>
nnoremap <buffer><silent> p
			\ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
nnoremap <buffer><silent> e
			\ <Cmd>call ddu#ui#ff#do_action('expandItem', {'mode': 'toggle'})<CR>
nnoremap <buffer><expr> -
			\ ddu#ui#get_item()->get('__sourceName') == 'file' ?
			\	"<ESC><Cmd>call ddu#ui#do_action('itemAction', { 'name': 'narrow' , 'params': { 'path': '..' }})<CR>" :
			\	""
nnoremap <buffer><silent> q
			\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
autocmd CursorMoved <buffer> call s:update_cursor()
function! s:update_cursor()
	sign unplace 100
	sign define cursor text=>> texthl=Constant
	execute printf('sign place 100 line=%d name=cursor buffer=%s',
		\ '.'->line(), '%'->bufnr())
endfunction
'''
ddu-ff-filter = '''
nnoremap <buffer> <CR>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> q
			\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
inoremap <buffer> <C-p>
			\ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
inoremap <buffer> <C-e>
			\ <Cmd>call ddu#ui#ff#do_action('echoPath')<CR>
inoremap <buffer><expr> <CR>
			\ ddu#ui#get_item()->get('__sourceName') == 'file' ?
			\	ddu#ui#get_item()->get('action')->get('isDirectory') ?
			\		"<ESC><Cmd>call ddu#ui#do_action('itemAction', { 'name': 'narrow' })<CR>" :
			\		"<ESC><Cmd>call ddu#ui#do_action('itemAction')<CR>" :
			\	"<ESC><Cmd>call ddu#ui#do_action('itemAction')<CR>"
inoremap <buffer> <C-t>
			\ <ESC><Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'tabnew'}})<CR>
inoremap <buffer> <C-o>
			\ <ESC><Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'split'}})<CR>
inoremap <buffer> <C-v>
			\ <ESC><Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'vsplit'}})<CR>
inoremap <buffer> <C-n>
			\ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')+1,0)<Bar>redraw")<CR>
inoremap <buffer> <C-p>
			\ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')-1,0)<Bar>redraw")<CR>
inoremap <buffer> <C-s>
			\ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
inoremap <buffer> <C-a>
			\ <Cmd>call ddu#ui#ff#do_action('toggleAllItems')<CR>
inoremap <buffer> <C-l>
			\ <ESC><Cmd>call ddu#ui#ff#do_action('leaveFilterWindow')<CR>
inoremap <buffer> <C-j>
			\ <ESC><Cmd>call ddu#ui#ff#do_action('kensaku')<CR>
inoremap <buffer> <C-q>
			\ <ESC><Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-filer = '''
nnoremap <buffer><expr> <CR>
			\ ddu#ui#get_item()->get('isTree', v:false) ?
			\ "<Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>" :
			\ "<Cmd>call ddu#ui#do_action('itemAction')<CR>"
nnoremap <buffer><silent> e
			\ <Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>
nnoremap <buffer><silent> p
			\ <Cmd>call ddu#ui#do_action('togglePreview')<CR>
nnoremap <buffer><silent> s
			\ <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> o
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'split'}})<CR>
nnoremap <buffer><silent> v
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
nnoremap <buffer><silent> t
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'tabnew'}})<CR>
nnoremap <buffer><silent> a
			\ <Cmd>call ddu#ui#do_action('chooseAction')<CR>
nnoremap <buffer><silent> %
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'newFile'})<CR>
nnoremap <buffer><silent> d
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'newDirectory'})<CR>
nnoremap <buffer><silent> R
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'rename'})<CR>
nnoremap <buffer><silent> q
			\ <Cmd>call ddu#ui#do_action('quit')<CR>
'''

# 補完Source

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_old'
on_source = 'ddu.vim'

[[plugins]]
repo = 'flow6852/ddu-source-qf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-vim-ui-select'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-command_history'
on_source = 'ddu.vim'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-jumplist'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-tab'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-floaterm'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-window'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-treesitter'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-dein_update'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-dummy'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-action'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-source-nvim-notify'
on_source = 'ddu.vim'

# 補完Filter
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-filter-matcher_regex'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-filter-converter_highlight'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Milly/ddu-filter-kensaku'
depends = ['kensaku.vim']
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-filter-converter_file_icon'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-filter-converter_file_info'
on_source = 'ddu.vim'

# 補完Kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-word'
on_source = 'ddu.vim'

# カラム
[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

# icon
[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

# command
[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'ddu.vim'
