[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_source = 'denops.vim'
hook_source = '''
let s:ddu_config_json =<< trim MARK
	{
		"ui": "ff",
		"uiOptions": {
			"filer": {
				"toggle": true
			}
		},
		"uiParams": {
			"ff": {
				"prompt": "> ",
				"filterSplitDirection": "floating",
				"split": "floating",
				"floatingBorder": "rounded",
				"floatingTitlePos": "center",
				"previewFloating":true,
				"previewFloatingBorder": "rounded",
				"previewFloatingTitle": [ ["Preview", "String"] ],
				"previewFloatingTitlePos": "center",
				"previewWindowOptions": [ ["&signcolumn", "no"], ["&wrap", 0], ["&number", 0] ]
			},
			"filer": {
				"split": "vertical",
				"splitDirection": "topleft",
				"sortTreesFirst": true
			}
		},
		"filterParams": {
			"matcher_fzf": {
				"highlightMatched": "String"
			},
			"matcher_substring": {
				"highlightMatched": "String"
			}
		},
		"kindOptions": {
			"file": {
				"defaultAction": "open"
			},
			"floaterm": {
				"defaultAction": "open"
			},
			"ui_select": {
				"defaultAction": "select"
			},
			"command_history": {
				"defaultAction": "execute"
			},
			"help": {
				"defaultAction": "open"
			},
			"dein_update": {
				"defaultAction": "viewDiff"
			},
			"window": {
				"defaultAction": "open"
			},
			"tab": {
				"defaultAction": "open"
			}
		},
		"actionOptions": {
			"echo": {
				"quit": false
			},
			"echoDiff": {
				"quit": false
			}
		},
		"sourceOptions": {
			"rg": {
				"matchers": ["converter_display_word", "matcher_fzf"]
			},
			"file_rec": {
				"matchers": ["matcher_fzf"],
				"converters": ["converter_file_icon"]
			},
			"file_external": {
				"matchers": ["matcher_fzf"],
				"converters": ["converter_file_icon"]
			},
			"dummy": {
				"matchers": []
			},
			"dein_update": {
				"matchers": ["matcher_dein_update"]
			},
			"_": {
				"matchers": ["matcher_fzf"]
			}
		}
	}
MARK

let s:ddu_config_json = s:ddu_config_json->join('')->json_decode()

call ddu#custom#patch_global(s:ddu_config_json)

" jsonだと式が書けないので、レイアウト周りはここで設定する

let s:winCol = &columns / 8
let s:winWidth = &columns - (&columns / 4)
let s:winRow = &lines / 8
let s:winHeight = &lines - (&lines / 4)

function! s:set_size() abort
	" window自体は左上が始点となる
	let s:ddu_config_json['uiParams']['ff']['winCol'] = s:winCol
	let s:ddu_config_json['uiParams']['ff']['winRow'] = s:winRow
	let s:ddu_config_json['uiParams']['ff']['winWidth'] = s:winWidth
	let s:ddu_config_json['uiParams']['ff']['winHeight'] = s:winHeight
	call ddu#custom#patch_global(s:ddu_config_json)
endfunction

call s:set_size()

" verticalオプションを使わないのもあって、previewの始点は左下になってる
" あまりキレイじゃないのだ...
call ddu#custom#patch_local('ui_filter_preview_layout', {
			\ 'uiParams': {
			\	'ff': {
			\		'startFilter': v:true,
			\		'autoAction': { 'name': 'preview' },
			\		'winCol': s:winCol,
			\		'winRow': s:winRow,
			\		'winWidth': s:winWidth / 2,
			\		'winHeight': s:winHeight,
			\		'previewCol': s:winCol + s:winWidth / 2 + 2,
			\		'previewRow': s:winRow + s:winHeight + 5,
			\		'previewWidth': s:winWidth / 2,
			\		'previewHeight': s:winHeight + 3,
			\	}
			\}
			\})

call ddu#custom#patch_local('ui_filter_preview_horizontal_layout', {
			\ 'uiParams': {
			\	'ff': {
			\		'startFilter': v:true,
			\		'autoAction': { 'name': 'preview' },
			\		'previewSplit': 'horizontal',
			\		'winCol': s:winCol,
			\		'winRow': &lines / 2,
			\		'winWidth': s:winWidth,
			\		'winHeight': &lines / 2 - 8,
			\		'previewCol': s:winCol,
			\		'previewRow': 0,
			\		'previewWidth': s:winWidth,
			\		'previewHeight': &lines / 2 - 8,
			\	}
			\}
			\})

call ddu#custom#patch_local('ui_filter_layout', {
			\ 'uiParams': {
			\	'ff': {
			\		'startFilter': v:true,
			\		'winCol' : s:winCol,
			\		'winWidth' : s:winWidth,
			\		'winRow' : s:winRow,
			\		'winHeight' : s:winHeight,
			\	}
			\}
			\})

call ddu#custom#patch_local('ui_preview_layout', {
			\ 'uiParams': {
			\	'ff': {
			\		'autoAction': { 'name': 'preview' },
			\		'winCol' : s:winCol,
			\		'winWidth' : s:winWidth / 2,
			\		'winRow' : s:winRow,
			\		'winHeight' : s:winHeight,
			\		'previewCol' : s:winCol + 2,
			\		'previewWidth' : s:winWidth / 2,
			\		'previewRow' : s:winRow,
			\		'previewHeight' : s:winHeight,
			\	}
			\}
			\})

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]

" telescopeのREADMEの順っぽく設定していく
" File
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Files', 'FloatBorder']],
			\		}
			\ },
			\ 'sources': [{'name': 'file_rec', 'params': {}}]
			\ })<CR>
nmap <silent> [ddu]g <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Files', 'FloatBorder'], ['Git', 'FloatBorder']],
			\		}
			\ },
			\ 'sources': [{
			\	'name': 'file_external',
			\	'params': { 'cmd': ['git', 'ls-files'] }
			\ }]
			\ })<CR>
" live grep
nmap <silent> [ddu]r <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'ignoreEmpty': v:false,
			\			'autoResize': v:false,
			\			'floatingTitle': [['Live Grep', 'String']],
			\		}
			\ },
			\ 'sources': [
			\	{
			\		'name': 'rg',
			\ 		'options': {'matchers': [], 'volatile': v:true},
			\	},
			\ ],
			\})<CR>

" Vim 関連
nmap <silent> [ddu]b <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Buffer', 'Blue']],
			\		}
			\ },
			\ 'sources': [{'name': 'buffer'}],
			\ })<CR>
nmap <silent> [ddu]c <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Command History', 'FloatBorder']],
			\			'autoAction': {},
			\		}
			\ },
			\ 'sources': [{'name': 'command_history'}],
			\ })<CR>
nmap <silent> [ddu]h <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Help', 'FloatBorder']],
			\		}
			\ },
			\ 'sources': [{'name': 'help', 'params': {}}],
			\ })<CR>
" QuickFix
nmap <silent> [ddu]q <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'prompt': 'qf',
			\			'floatingTitle': [['QuickFix', 'String']],
			\		}
			\ },
			\ 'sources': [
			\	{
			\		'name': 'qf',
			\		'params': {
			\			'isSubset': v:true,
			\			'format': '%p\|%t',
			\ 		}
			\	},
			\ ],
			\})<CR>
nmap <silent> [ddu]j <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['JumpList', 'String']],
			\		}
			\ },
			\ 'sources': [{'name': 'jumplist', 'params': {}}],
			\ })<CR>
nmap <silent> [ddu]t <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Tab', 'FloatBorder']],
			\			'autoAction': { 
			\				'name': 'preview',
			\				'params': { 'border': ['+', '-', '+', '\|'] }
			\			},
			\		}
			\ },
			\ 'sources': [{'name': 'tab', 'params': { 'format': 'tab\|%n:%T:%w' }}]
			\ })<CR>
nmap <silent> [ddu]w <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Window', 'FloatBorder']],
			\			'autoAction': { 
			\				'name': 'preview',
			\			},
			\		}
			\ },
			\ 'sources': [{'name': 'window', 'params': { 'format': 'tab\:%tn:%T:%w:%wi' }}]
			\ })<CR>
nmap <silent> [ddu]L <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Line', 'String']],
			\		}
			\ },
			\ 'sources': [{'name': 'line', 'params': {}}],
			\ })<CR>

" Neovim LSP 関連
" lsp
nmap <silent> [ddu]lr <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\	'ff': {
			\		'floatingTitle': [['Lsp References', 'FloatBorder']],
			\	}
			\ },
			\ 'sources': [
			\	{'name': 'lsp_references'}
			\ ],
			\ })<CR>
nmap <silent> [ddu]ld <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\	'ff': {
			\		'floatingTitle': [['Lsp Definition', 'FloatBorder']],
			\	}
			\ },
			\ 'sources': [
			\	{'name': 'lsp_definition', 'params': { 'method': 'textDocument/definition' }}
			\ ],
			\ })<CR>
nmap <silent> [ddu]ls <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_layout',
			\ 'uiParams': {
			\	'ff': {
			\		'floatingTitle': [['Lsp Symbol', 'FloatBorder']],
			\	}
			\ },
			\ 'sources': [
			\	{'name': 'lsp_documentSymbol'},
			\	{'name': 'lsp_workspaceSymbol'}
			\ ],
			\ })<CR>
nmap <silent> [ddu]lh <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_preview_layout',
			\ 'uiParams': {
			\	'ff': {
			\		'floatingTitle': [['Lsp Hierarchy', 'FloatBorder']],
			\		'displayTree': v:true,
			\		'startFilter': v:false,
			\		'previewSplit': 'vertical',
			\	}
			\ },
			\ 'sources': [
			\	{'name': 'lsp_hierarchy', 'params': { 'method': 'callHierarchy/incomingCalls' }},
			\	{'name': 'lsp_hierarchy', 'params': { 'method': 'callHierarchy/outgoingCalls' }}
			\ ],
			\ })<CR>

" 他のプラグインとの連携
nmap <silent> [ddu]T <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_preview_horizontal_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Floaterm', 'FloatBorder']],
			\		}
			\ },
			\ 'sources': [{'name': 'floaterm'}]
			\ })<CR>
nmap <silent> [ddu]d <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'name': 'ui_filter_layout',
			\ 'uiParams': {
			\		'ff': {
			\			'floatingTitle': [['Dein', 'Black']],
			\			'autoAction': {},
			\		}
			\ },
			\ 'sources': [{'name': 'dein'}],
			\ })<CR>

" filer 表示
nmap <silent> [ddu]e <Cmd>call ddu#start({
			\ 'ui': 'filer',
			\ 'sources': [{'name': 'file'}],
			\ 'sourceOptions': {'_': {'columns': ['icon_filename']}},
			\ 'uiParams': {
			\	'filer': {
			\		'split': 'vertical',
			\		'splitDirectoin': 'topleft',
			\		'winWidth': &columns / 6,
			\	}
			\ },
			\ })<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-ff = '''
setlocal cursorline
setlocal signcolumn=yes
nnoremap <buffer><silent> <CR>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> t
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'tabnew'}})<CR>
nnoremap <buffer><silent> o
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'split'}})<CR>
nnoremap <buffer><silent> v
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'vsplit'}})<CR>
nnoremap <buffer><silent> s
			\ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> i
			\ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent> c
			\ <Cmd>call ddu#ui#ff#do_action('closeFilterWindow')<CR>
nnoremap <buffer><silent> p
			\ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
nnoremap <buffer><silent> e
			\ <Cmd>call ddu#ui#ff#do_action('expandItem', {'mode': 'toggle'})<CR>
nnoremap <buffer><silent> q
			\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
autocmd CursorMoved <buffer> call s:update_cursor()
function! s:update_cursor()
	sign unplace 100
	sign define cursor text=>> texthl=Constant
	execute printf('sign place 100 line=%d name=cursor buffer=%s',
		\ '.'->line(), '%'->bufnr())
endfunction
'''
ddu-ff-filter = '''
nnoremap <buffer> <CR>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> q
			\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
inoremap <buffer> <C-p>
			\ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
inoremap <buffer> <CR>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
inoremap <buffer> <C-t>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'tabnew'}})<CR>
inoremap <buffer> <C-o>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'split'}})<CR>
inoremap <buffer> <C-v>
			\ <Cmd>call ddu#ui#ff#do_action('itemAction', {'params': {'command': 'vsplit'}})<CR>
inoremap <buffer> <C-n>
			\ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')+1,0)<Bar>redraw")<CR>
inoremap <buffer> <C-p>
			\ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')-1,0)<Bar>redraw")<CR>
inoremap <buffer> <C-s>
			\ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
inoremap <buffer> <C-a>
			\ <Cmd>call ddu#ui#ff#do_action('toggleAllItems')<CR>
inoremap <buffer> <C-l>
			\ <ESC><Cmd>call ddu#ui#ff#do_action('leaveFilterWindow')<CR>
inoremap <buffer> <C-q>
			\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-filer = '''
nnoremap <buffer><expr> <CR>
			\ ddu#ui#get_item()->get('isTree', v:false) ?
			\ "<Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>" :
			\ "<Cmd>call ddu#ui#do_action('itemAction', {'name': 'open'})<CR>"
nnoremap <buffer><silent> <Space>
			\ <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> o
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'split'}})<CR>
nnoremap <buffer><silent> v
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
nnoremap <buffer><silent> t
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'tabnew'}})<CR>
nnoremap <buffer><silent> %
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'newFile'})<CR>
nnoremap <buffer><silent> d
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'newDirectory'})<CR>
nnoremap <buffer><silent> R
			\ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'rename'})<CR>
nnoremap <buffer><silent> q
			\ <Cmd>call ddu#ui#do_action('quit')<CR>
'''

# 補完Source

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'flow6852/ddu-source-qf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-vim-ui-select'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-command_history'
on_source = 'ddu.vim'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-jumplist'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-tab'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-floaterm'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-window'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-treesitter'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-dein_update'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-dummy'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'

# 補完Filter
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-filter-converter_file_icon'
on_source = 'ddu.vim'

# 補完Kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

# カラム
[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

# icon
[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

# command
[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'ddu.vim'
