[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = '''
let g:tex_flavor = 'latex'
'''
hook_source = '''
"let g:vimtex_view_general_viewer = 'displayline'
"let g:vimtex_view_general_options = '-r @line @pdf @tex'
"let g:vimtex_compiler_latexmk = { 'continuous': 0 }
"let g:vimtex_quickfix_open_on_warning = 0
"call vimtex#init()
"call ddc#custom#patch_filetype(['tex'], 'sourceOptions', #{
"      \   omni: #{
"      \     mark: 'omni',
"      \     forceCompletionPattern: g:vimtex#re#deoplete,
"      \     dup: 'keep',
"      \   },
"      \ })
"call ddc#custom#patch_filetype(['tex'], 'sourceParams', #{
"      \   omni: #{ omnifunc: 'vimtex#complete#omnifunc' },
"      \ })
'''

